controller_manager:
  ros__parameters:
    update_rate: 25  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - FR_screw
      - BR_screw
      - BL_screw
      - FL_screw
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
