world: "cave_world" # select either "empty_world", "boxes_world", "terrain_world" or "cave_world"

sensors:
  whiskers:
    enable_whiskers: 'enable'  # 'enable' or 'disable'
    bottom_whisker_length: 0.15
    side_whisker_length: 0.15
    map_type: "OnlyWhenDeflected" # "Always" or "OnlyWhenDeflected"
  camera:
    enable_camera: 'enable' # 'enable' or 'disable'
    camera_angle: 0.0
