<?xml version="1.0"?>
<!-- June 2022 -->
<!-- Author: Walid Remmas -->
<!-- Contact: walid.remmas@Å§altech.ee -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:property name="whisker_mesh_file" value="file://$(find rm3_gazebo)/urdf/meshes/whisker.dae"/>
  <xacro:property name="whisker_array_mesh_file" value="file://$(find rm3_gazebo)/urdf/meshes/whisker_array.dae"/>

  
  <xacro:property name="whisker_radius" value="0.002"/>
  <xacro:property name="whisker_array_mass" value="2.75"/>

  <xacro:property name="whisker_damping" value="2.0"/>
  <xacro:property name="whisker_friction" value="0.0"/>
  <xacro:property name="whisker_revolute_effort_limit" value="0.1"/>
  <xacro:property name="whisker_revolute_vel_limit" value="${pi/2.0}"/>

  <xacro:property name="whisker_x" value="-0.0345"/>
  <xacro:property name="whisker_x_bias" value="0.075"/>
  <xacro:property name="whisker_y" value="0.001"/>
  <xacro:property name="whisker_z" value="0.02"/>

  <xacro:property name="whisker_collision_box_x" value="0.6"/>
  <xacro:property name="whisker_collision_box_y" value="0.08"/>
  <xacro:property name="whisker_collision_box_z" value="0.07"/>

  <xacro:property name="magnet_size_x" value="0.005"/>
  <xacro:property name="magnet_size_y" value="0.005"/>
  <xacro:property name="magnet_size_z" value="0.005"/>
  <xacro:property name="magnet_mass" value="1e-4"/>

  <xacro:macro name="whisker_feedback" params="joint_name">
      <joint name="${joint_name}">
        <state_interface name="position"/>
      </joint>
  </xacro:macro>


 <!-- WHISKER DEFITION -->
  <xacro:macro name="whisker" params="name id parent length *origin">
      <!-- Magnet around x axis is connected to base_array and rotating around x-->
      <joint name="${name}_whisker_${id}_x" type="revolute">
          <xacro:insert_block name="origin"/>
          <parent link="${parent}"/>
          <child link="${name}_whisker_x_link_${id}"/>
          <axis xyz="0 1 0" />
          <limit
          lower="${-pi/2}"
          upper="${pi/2}"
          effort="${whisker_revolute_effort_limit}"
          velocity="${whisker_revolute_vel_limit}" />
          <dynamics
            damping="${whisker_damping}"
            friction="${whisker_friction}"
          />
      </joint>

      <link name="${name}_whisker_x_link_${id}">
          <inertial>
          <mass value="${magnet_mass}"/>
          <inertia
            ixx="${(1.0/12.0) * magnet_mass * (magnet_size_y ** 2 + magnet_size_z ** 2)}"
            ixy="0.0"
            ixz="0.0"
            iyy="${(1.0/12.0) * magnet_mass * (magnet_size_x ** 2 + magnet_size_z ** 2)}"
            iyz="0.0"
            izz="${(1.0/12.0) * magnet_mass * (magnet_size_y ** 2 + magnet_size_x ** 2)}"/>
        </inertial>
        <visual>
            <geometry>
              <box size="0.005 0.005 0.005" />
            </geometry>
        </visual>
      </link>

      <!-- Whisker fixed on magnet x and rotating around y-->
      <joint name="${name}_whisker_${id}_y" type="revolute">
          <origin xyz="0 0 0" rpy="0 0 0" />
          <parent link="${name}_whisker_x_link_${id}"/>
          <child link="${name}_whisker_y_link_${id}"/>
          <axis xyz="1 0 0" />
          <limit
            lower="${-pi/2}"
            upper="${pi/2}"
            effort="${whisker_revolute_effort_limit}"
            velocity="${whisker_revolute_vel_limit}" />
          <dynamics
              damping="${whisker_damping}"
              friction="${whisker_friction}"
              />
      </joint>

      <link name="${name}_whisker_y_link_${id}">
          <inertial>
              <origin xyz="0 0 0" rpy="0 0 0" />
                      <mass value="${magnet_mass}"/>
                      <inertia
                        ixx="${(1.0/12.0) * magnet_mass * (magnet_size_y ** 2 + magnet_size_z ** 2)}"
                        ixy="0.0"
                        ixz="0.0"
                        iyy="${(1.0/12.0) * magnet_mass * (magnet_size_x ** 2 + magnet_size_z ** 2)}"
                        iyz="0.0"
                        izz="${(1.0/12.0) * magnet_mass * (magnet_size_y ** 2 + magnet_size_x ** 2)}"/>
          </inertial>
          <visual>
              <origin xyz="0 0 ${length/2}"
                      rpy="0 0 0" />
              <geometry>
                <cylinder radius="${whisker_radius}" length="${length}"/>
              </geometry>
          </visual>

          <collision>
              <origin xyz="0 0 ${length/2}"
                      rpy="0 0 0" />
              <geometry>
                <cylinder radius="${whisker_radius}" length="${length}"/>
              </geometry>
          </collision>
      </link>

      <gazebo reference="${name}_whisker_${id}_x">
          <implicitSpringDamper>true</implicitSpringDamper>
          <springStiffness>5.7</springStiffness>
          <springReference>0.0</springReference>
      </gazebo>

      <gazebo reference="${name}_whisker_${id}_y">
          <implicitSpringDamper>true</implicitSpringDamper>
          <springStiffness>5.7</springStiffness>
          <springReference>0.0</springReference>
      </gazebo>

      <gazebo reference="${name}_whisker_y_link_${id}">
        <material>Gazebo/White</material>
        <mu1>0</mu1>
        <mu2>0</mu2>
      </gazebo>


      <ros2_control name="GazeboSystem" type="system">
        <hardware>
          <plugin>gazebo_ros2_control/GazeboSystem</plugin>
        </hardware>
         <xacro:whisker_feedback joint_name="${name}_whisker_${id}_x"/>
         <xacro:whisker_feedback joint_name="${name}_whisker_${id}_y"/>
      </ros2_control>

  </xacro:macro>


 <!-- WHISKER ARRAY DEFITION -->
  <xacro:macro name="whisker_array" params="name whisker_length *origin">
      <joint name="${name}_whisker_array" type="fixed">
          <xacro:insert_block name="origin"/>
          <parent link="chassis"/>
          <child link="${name}_whisker_array_link"/>
      </joint>

      <link name="${name}_whisker_array_link">
        <inertial>
          <!-- <xacro:insert_block name="origin"/> -->
          <mass value="${whisker_array_mass}" />
          <inertia
            ixx="${(1/12)*whisker_array_mass*(whisker_collision_box_z**2 + whisker_collision_box_y**2)}"
            ixy="0.0"
            ixz="0.0"
            iyy="${(1/12)*whisker_array_mass*(whisker_collision_box_z**2 + whisker_collision_box_x**2)}"
            iyz="0.0"
            izz="${(1/12)*whisker_array_mass*(whisker_collision_box_x**2 + whisker_collision_box_y**2)}"/>
        </inertial>
          <visual>
              <geometry>
                <mesh filename="${whisker_array_mesh_file}" scale="1 1 1"/>
              </geometry>
          </visual>
      </link>

      <gazebo reference="${name}_whisker_array_link">
        <material>Gazebo/DarkGrey</material>
      </gazebo>

      <!-- whisker #1 -->
      <xacro:whisker name="${name}" id = "1" parent= "${name}_whisker_array_link" length = "${whisker_length}">
        <origin xyz="${whisker_x + -3*whisker_x_bias} ${whisker_y} ${whisker_z}"
                rpy="0 0 0" />
      </xacro:whisker>
      <!-- whisker #2 -->
      <xacro:whisker name="${name}" id = "2" parent= "${name}_whisker_array_link" length = "${whisker_length}" >
        <origin xyz="${whisker_x + -2*whisker_x_bias} ${whisker_y} ${whisker_z}"
                rpy="0 0 0" />
      </xacro:whisker>
      <!-- whisker #3 -->
      <xacro:whisker name="${name}" id = "3" parent= "${name}_whisker_array_link" length = "${whisker_length}">
        <origin xyz="${whisker_x + -whisker_x_bias} ${whisker_y} ${whisker_z}"
                rpy="0 0 0" />
      </xacro:whisker>
      <!-- whisker #4 -->
      <xacro:whisker name="${name}" id = "4" parent= "${name}_whisker_array_link" length = "${whisker_length}">
        <origin xyz="${whisker_x + -0*whisker_x_bias} ${whisker_y} ${whisker_z}"
                rpy="0 0 0" />
      </xacro:whisker>
      <!-- whisker #5 -->
      <xacro:whisker name="${name}" id = "5" parent= "${name}_whisker_array_link" length = "${whisker_length}">
        <origin xyz="${whisker_x + whisker_x_bias} ${whisker_y} ${whisker_z}"
                rpy="0 0 0" />
      </xacro:whisker>
      <!-- whisker #6 -->
      <xacro:whisker name="${name}" id = "6" parent= "${name}_whisker_array_link" length = "${whisker_length}">
        <origin xyz="${whisker_x + 2*whisker_x_bias} ${whisker_y} ${whisker_z}"
                rpy="0 0 0" />
      </xacro:whisker>
      <!-- whisker #7 -->
      <xacro:whisker name="${name}" id = "7" parent= "${name}_whisker_array_link" length = "${whisker_length}">
        <origin xyz="${whisker_x + 3*whisker_x_bias} ${whisker_y} ${whisker_z}"
                rpy="0 0 0" />
      </xacro:whisker>
      <!-- whisker #8 -->
      <xacro:whisker name="${name}" id = "8" parent= "${name}_whisker_array_link" length = "${whisker_length}">
        <origin xyz="${whisker_x + 4*whisker_x_bias} ${whisker_y} ${whisker_z}"
                rpy="0 0 0" />
      </xacro:whisker>
  </xacro:macro>
</robot>
